# Dependencies
markdown:    kramdown
highlighter: pygments

# Setup
encoding:      utf-8
title:         Katie & Lucas
tagline:       blog
description:   Katie & Lucas' Wedding Site
url:           http://katie-and-lucas.com
permalink:     /blog/:title
commentsystem:
disqus:
paginate:      5

author:
  name:  Lucas Yamanishi
  url:   https://google.com/+LucasYamanishi
  email: lucas.yamanishi@gmail.com

# Custom vars
icon:  /assets/images/mon.png
cover: /assets/images/k+l.jpeg

social:
  - icon: github
    url:  https://github.com/lamawithonel/wedding_site
    desc: Fork this site on github

  - icon: feed
    url:  http://katie-and-lucas.com/atom.xml
    desc: Subscribe to our feed
    
menu:
  - title: Home
    url:   /

  - title: About Us
    url:   /about.html

errors:
    404: Whatever you were looking for it isn't here.  But isn't this font beautiful?
    
copyright:
  author:     Lucas Yamanishi
  url:        http://katie-and-lucas.com
  type_title: All rights reserved
  type_url:
